---

- name: Apache2 | Install required packages
  dnf: name=httpd state=installed
  tags: apache2


- name: MariaDB | Install Packages
  dnf: name={{ item }} state=installed
  with_items:
    - mariadb-server
    - mariadb
    - python-mysql
  notify: Start mariadb

- name: MariaDB | Test
  shell: ls /root/.my.cnf | wc -l
  register: database_config

#- name: MariaDB | Update mysql root password for all root accounts from local servers
#  mysql_user: login_user=root
#              login_password={{ mariadb.current_password }}
#              name=root
#              host={{ item }}
#              password={{ mariadb.root_password }}
#              priv=*.*:ALL,GRANT
#  with_items:
#    - "{{ ansible_hostname }}"
#    - 127.0.0.1
#    - ::1
#    - localhost
#  when: database_config == 0
#  notify: Restart mariadb

#- name: MariaDB | Write file my.cnf
#  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

#- name: MariaDB | Write file my.cnf
#  template: src=my.cnf.j2 dest={{ ansible_env.HOME }}/.my.cnf owner={{ ansible_env.LOGNAME }} mode=0600
#
#- name: MariaDB | Remove the MySQL test database
#  mysql_db: db=test state=absent

# This role deploys the PHP5 processes and sets up settings.

- name: PHP5 | Install required packages.
  action: dnf pkg={{ item }} state=installed
  with_items:
    - php
    - php-devel
    - php-pear
    - php-cli
    - php-dbg
    - php-mysqlnd
    - php-pecl-jsonc-devel
  tags: php5
  notify: Restart apache

- name: PHP5 | Configuration /etc/php.ini
  template: src=etc-php5-apache2-php-ini.j2 dest=/etc/php.ini mode=0644
  notify: Restart apache

#- name: PHP5 | Configuration /etc/php5/cli/php.ini
#  template: src=etc-php5-cli-php-ini.j2 dest=/etc/php5/cli/php.ini mode=0644

- name: PHP5 | PHPDev | Update pear channels
  command: pear update-channels

- name: PHP5 | PHPDev | Update pear packages
  command: pear upgrade-all

- name: PHP | PHPDev | Set pear auto-discover
  command: pear config-set auto_discover 1

- name: PHP | PHPDev | Pear install the PHP QA Toolchain
  command: pear install pear.phpqatools.org/phpqatools creates=/usr/bin/phpunit
  # this fails often (dns problems, pear problems, etc. So just ignore the errors and continue.)
  ignore_errors: true

# This role deploys the phpmyadmin processes and sets up settings.

- name: Phpmyadmin | Install Phpmyadmin
  dnf: name=phpMyAdmin state=present
  notify: Restart apache

- name: Phpmyadmin | Add symlink for phpmyadmin
  file: src=/usr/share/phpMyAdmin dest=/var/www/phpmyadmin state=link

- name: Install WP-CLI
  get_url: url="https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar" dest="/usr/local/bin/wp" mode=0755
